# Generated by Django 2.2.3 on 2019-07-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0002_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Close',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
