# Generated by Django 2.2.3 on 2019-07-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0003_auto_20190725_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='close',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
