# Generated by Django 2.2.3 on 2019-07-25 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stc', '0004_close_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='close',
            old_name='value',
            new_name='price',
        ),
    ]
